# host, port for callback google authorization
# oauth_callback_host_port: localhost:8080

# Конфигурация Google Drive
config_google_drives:
  - id: "0"
    google_credentials_file: "google_credentials.json"
    upload_copies_count: 3
    folder_id: "1bdlpF5xWqyNg0vXBLxH5ZbpzDwIkIuw3"
  
  # Пример дополнительной конфигурации для второго диска
  # - id: "1"
  #   google_credentials_file: "google_credentials_secondary.json"
  #   upload_copies_count: 5
  #   folder_id: "1bdlpF5xWqyNg0vXBLxH5ZbpzDwIkIuw3"