# host, port for callback google authorization
# oauth_callback_host_port: localhost:8080

# Конфигурация Google Drive
config_google_drives:
  - id: "0"
    google_credentials_file: "google_credentials_0.json"
    upload_copies_count: 1
    folder_id: "1bdlpF5xWqyNg0vXBLxH5ZbpzDwIkIuw3"
    enable: false

  - id: "1"
    google_credentials_file: "google_credentials_1.json"
    upload_copies_count: 1
#   folder_id from url folder https://drive.google.com/drive/u/2/folders/1SY2A2cblPWO7VzlELhmt7tjW5rD7GMKG
    folder_id: "1SY2A2cblPWO7VzlELhmt7tjW5rD7GMKG"
    enable: true
