# host, port for callback google authorization
# oauth_callback_host_port: localhost:8080

# Конфигурация Google Drive
config_google_drives:
  - id: "0"
    google_credentials_file: "google_credentials_0.json"
    upload_copies_count: 1
    folder_id: "1bdlpF5xWqyNg0vXBLxH5ZbpzDwIkIuw3"
    enable: true

  - id: "TidyArchiver"
    google_credentials_file: "google_credentials_TidyArchiver.json"
    upload_copies_count: 1
    folder_id: ""
    enable: true

  - id: "TidyArchiver0"
    google_credentials_file: "google_credentials_TidyArchiver0.json"
    upload_copies_count: 1
    folder_id: ""
    enable: true

  - id: "TidyArchiver1"
    google_credentials_file: "google_credentials_TidyArchiver1.json"
    upload_copies_count: 1
    folder_id: ""
    enable: true
